ignore-build-dependencies = true
ignore-dev-dependencies = true

accepted = [
    "Unlicense",
    "WTFPL",
    "Apache-2.0",
    "ISC",
    "MIT",
    "BSL-1.0",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "OpenSSL",
    "Zlib",
    "Unicode-DFS-2016",
]
workarounds = [
    "ring",
]